language: cpp

compiler:
- clang
- gcc-4.8

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - lua5.1

script: ./CIbuild.sh

env:
  - TRAVIS_MCSERVER_BUILD_TYPE=RELEASE MCSERVER_PATH=./MCServer
  - TRAVIS_MCSERVER_BUILD_TYPE=DEBUG   MCSERVER_PATH=./MCServer_debug

notifications:
  email:
    on_success: change
    on_failure: always
